FROM node:10-slim

LABEL version="1.30.4"
LABEL repository="http://github.com/kamilkisiela/graphql-inspector"
LABEL homepage="http://github.com/kamilkisiela/graphql-inspector"
LABEL maintainer="Kamil Kisiela <kamil.kisiela@gmail.com>"

ENV LOG_LEVEL "debug"

RUN yarn global add @graphql-inspector/cli@1.30.4 graphql

RUN mkdir /app
WORKDIR /app
