import {buildSchema, GraphQLSchema} from 'graphql';
import {diff} from '../src/diff';
import {printSchema} from '../src/location';
import {CheckConclusion} from '../src/types';

function getPrintedLine(schema: GraphQLSchema, line: number): string {
  const printed = printSchema(schema);

  return printed.split('\n')[line - 1];
}

const newSchema = buildSchema(/* GraphQL */ `
  type Post {
    id: ID!
    title: String!
    createdAt: String!
  }

  type Query {
    post: Post!
  }
`);

const oldSchema = buildSchema(/* GraphQL */ `
  type Post {
    id: ID
    title: String @deprecated(reason: "No more used")
    createdAt: String
    modifiedAt: String
  }

  type Query {
    post: Post!
    posts: [Post!]
  }
`);

test('should return 7 annotations and 7 changes and fail the check', async () => {
  const action = await diff({
    path: 'schema.graphql',
    schemas: {
      old: oldSchema,
      new: newSchema,
    },
  });

  expect(action.annotations).toHaveLength(7);
  expect(action.changes).toHaveLength(7);
  expect(action.conclusion).toBe(CheckConclusion.Failure);
});

test('annotations should match lines in schema file', async () => {
  const action = await diff({
    path: 'schema.graphql',
    schemas: {
      old: oldSchema,
      new: newSchema,
    },
  });

  // Field 'modifiedAt' was removed from object type 'Post'
  expect(getPrintedLine(oldSchema, action.annotations![0].start_line)).toBe(
    '  modifiedAt: String',
  );

  // Field 'Post.createdAt' changed type from 'String' to 'String!'
  expect(getPrintedLine(oldSchema, action.annotations![5].start_line)).toBe(
    '  createdAt: String',
  );
});

test.todo('should work with comments and descriptions'/*, async () => {
  const schemas = {
    old: buildSchema(`
      # This is an autogenerated file.
      # Please do not edit it directly.

      """
      Represents meta information about this service.
      """
      type Meta {
        """
        A short description of the service.
        """
        description: String!

        """
        Name of the service.
        """
        name: String!

        """
        Version number of the service.
        """
        version: String!
      }
    `),
    new: buildSchema(`
      # This is an autogenerated file.
      # Please do not edit it directly.

      """
      Represents a user of the application.
      """
      type User {
        """
        The user's email.
        """
        email: String!

        """
        The user's first name.
        """
        firstName: String!

        """
        The user's last name.
        """
        lastName: String!

        """
        The user's phone number.
        """
        phoneNumber: String!

        """
        A URL pointing to the user's public avatar.
        """
        avatarURL: String!
      }

      """
      Represents meta information about this service.
      """
      type Meta {
        """
        A short description of the service.
        """
        description: String!

        """
        Name of the service.
        """
        name: String!
      }
    `),
  };

  const action = await diff({
    path: 'schema.graphql',
    schemas,
  });

  expect(action.annotations).toHaveLength(2);

  // Type 'User' was added
  expect(getPrintedLine(schemas.new, action.annotations![0].start_line)).toBe(
    'type User {',
  );
  // Field 'version' was removed from object type 'Meta'
  expect(getPrintedLine(schemas.old, action.annotations![1].start_line)).toBe(
    '  version: String!',
  );
}*/);
